language: rust
rust:
  - stable

before_install:
  - cd cargo-test-cerussite

install:
  - cargo install --path .

script:
  - cargo test-cerussite -v

notifications:
  slack: kmc-jp:OsbOUDQMNlIePv2IhnFrMAKI
